### ISSUE TITLE
The following classes could not be instantiated: - android.support.design.widget.TextInputLayout

### ISSUE THREAD

**Issue by komalnikhare** [StylingAndroid/TextInputLayout#1]
hi @StylingAndroid ....

@kneth...

I am trying to use TextInputLayut but, getting error in my xml file which is ...

Exception raised during rendering: com.android.layoutlib.bridge.MockView cannot be cast to android.view.ViewGroup
Exception details are logged in Window > Show View > Error Log
The following classes could not be instantiated:
- android.support.design.widget.TextInputLayout (Open Class, Show Error Log)
  See the Error Log (Window > Show View) for more details.

java.lang.illegalstateException you need to use a theme.appcompat theme(or descendant)

 Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:34)
at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:103)
at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:96)

please help me to out of this

**Comment by StylingAndroid** [comment]
This isn't an issue with the code in this repo and this is a wholly inappropriate way of asking for free developer support on the design library components.

**Comment by komalnikhare** [comment]
@StylingAndroid ...

how can i resolve this , have latest library 23 but still getting Inflate error 
I am using Eclips not studio

**Comment by rock3r** [comment]
Hint: the error message you copy pasted tells you **exactly** what to do.

Note: Eclipse is officially EOL'd so you won't likely get _any_ support for it.
